### ISSUE TITLE
API adjustment - Create chart by passing element reference instead of DOM id

### ISSUE THREAD

**Issue by dinedal** [jcarver989/suave-charts#24]
Any chance I could do 

`chart = new Suave.LineChart(document.getElementById("chart"))`

instead of:

`chart = new Suave.LineChart("#chart")`

**Comment by jcarver989** [comment]
Sure, just added this functionality, it should work across all chart types.

**Comment by dinedal** [comment]
Awesome thanks, this helps a lot in cleaning up my code.
