### ISSUE TITLE
On chart remove, please remove tooltip elements?

### ISSUE THREAD

**Issue by dinedal** [jcarver989/suave-charts#28]
Discovered this when a remove happened while I was still hovered over a tool tip.

![image](https://cloud.githubusercontent.com/assets/606028/13941985/9f2f4808-efaa-11e5-91c8-aa1406a6d366.png)

As you can see, points went from many to one, left the hovering tooltip there.

![image](https://cloud.githubusercontent.com/assets/606028/13942000/c33c8242-efaa-11e5-8077-93481842f29c.png)

**Comment by jcarver989** [comment]
Thanks for reporting!
